In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/samplesuperstore.csv")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,01-05-2023,01-12-2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [4]:
df.shape

(10194, 21)

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

In [8]:
df['Sales']

0         16.448
1          3.540
2         11.784
3        272.736
4         19.536
          ...
10189     52.776
10190     20.720
10191      3.024
10192     90.930
10193      3.024
Name: Sales, Length: 10194, dtype: float64

In [9]:
df['Postal Code']

0        77095
1        60540
2        60540
3        60540
4        19143
         ...
10189    10009
10190    94533
10191    80538
10192    10009
10193      C0A
Name: Postal Code, Length: 10194, dtype: object

In [10]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [11]:
df['Postal Code'] = df['Postal Code'].fillna('Unknown')

In [12]:
df['Order ID'] = (
    df['Order ID']
    .str.strip()
    .str.title()
)

In [13]:
df['Order ID'].unique()

array(['Us-2023-103800', 'Us-2023-112326', 'Us-2023-141817', ...,
       'Us-2026-115427', 'Us-2026-156720', 'Ca-2026-143500'], dtype=object)

In [14]:
df['Order ID'].value_counts()

Order ID
Us-2026-100111    14
Us-2026-157987    12
Us-2025-108504    11
Us-2025-165330    11
Us-2025-105732    10
                  ..
Us-2023-149524     1
Us-2024-118948     1
Us-2026-101322     1
Us-2026-129805     1
Us-2026-162068     1
Name: count, Length: 5111, dtype: int64

In [22]:
df['Sales'].describe()

count    10194.000000
mean       228.225854
std        619.906839
min          0.444000
25%         17.220000
50%         53.910000
75%        209.500000
max      22638.480000
Name: Sales, dtype: float64

In [23]:
df.groupby('Customer Name')['Profit'].mean()

Customer Name
Aaron Bergman          21.557750
Aaron Hawkins          33.201382
Aaron Smayling        -25.357460
Adam Bellavance       114.143806
Adam Hart              14.059450
                         ...
Xylona Preis           19.881129
Yana Sorensen         148.191025
Yoseph Carroll        163.203625
Zuschuss Carroll      -33.295129
Zuschuss Donatelli     27.681189
Name: Profit, Length: 800, dtype: float64

In [24]:
pd.crosstab(
    df['Customer Name'],
    df['Region']
)

Region              Central  East  South  West
Customer Name
Aaron Bergman             3     0      0     3
Aaron Hawkins             0     5      1     5
Aaron Smayling            2     1      4     3
Adam Bellavance           3     7      3     5
Adam Hart                 2    10      3     5
...                     ...   ...    ...   ...
Xylona Preis             11     3      2    18
Yana Sorensen             0     1      4     7
Yoseph Carroll            3     3      0     2
Zuschuss Carroll         11     1      3    16
Zuschuss Donatelli        2     0      3     4

[800 rows x 4 columns]